In [105]:
from requests import get
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', None)

['MARTIN H S',
 'SEAGOVILLE H S',
 'KILLEEN H S',
 'WESTLAKE ALTER',
 'PLATO ACADEMY',
 'DR WRIGHT L LASSITER JR EARLY COLLEGE H S',
 'DAVENPORT H S',
 'JUNCTION H S',
 'HEMPHILL H S',
 'FLOYDADA COLLEGIATE H S',
 'ZAPATA H S',
 'HORIZON H S HARLINGEN’,
 'NORTHSIDE SCHOOL’,
 'LONDON H S’,
 'ARGYLE H S’,
 'GATESVILLE H S’,
 'MOISES E MOLINA H S’,
 'OZONA H S’,
 'KING H S’,
 'THE PHOENIX ACADEMY’,
 'KENNEDALE H S’,
 'ILTEXAS KELLER SAGINAW H S’,
 'CANYON LAKE H S’,
 'THE EXCEL CENTER FOR ADULTS AYW’,
 'LESTER DAVIS’,
 ['CHINA SPRING H S',
 'SOCORRO H S',
 'BRIDGE CITY H S',
 'QUANAH H S',
 'PREMIER HIGH SCHOOL-CANYON',
 'N GARLAND H S',
 'TRIUMPH PUBLIC HIGH SCHOOLS-EL PASO WEST',
 'SALADO H S',
 'BUSHLAND H S',
 'MABANK H S',
 'SAM HOUSTON H S',
 'COLUMBIA H S',
 'YSLETA H S',
 'KASHMERE H S',
 'KERR H S',
 'ILTEXAS GARLAND H S',
 'CAREER & TECH ED CTR',
 'SOUTH HILLS H S',
 'LIGHTHOUSE HIGH',
 'PORT NECHES-GROVES H S',
 'BLANSON CTE H S',
 'ANSON H S',
 'ROUND ROCK H S',
 'GAINESVILLE H S',
 'RIO HONDO H S',
 'SCHOOL OF BUSINESS AND MANAGEMENT']
  
 'LEANDER H S’,
 'TASCOSA H S’,
 'CEDAR RIDGE H S’,
 'WALLACE ACCELERATED H S’,
 'HUNTSVILLE H S’,
 'SMITHSON VALLEY H S’,
 'EL CAMPO H S’,
 'DEVINE H S’,
 'TOMBALL H S’,
 'REAGAN COUNTY H S’,
 'ALTER SCH’,
 'CANEY CREEK H S’,
 'FRUITVALE H S’,
 'NEW WAVERLY H S’,
 'LBJ ECHS’,
 'HIGHLAND PARK H S’,
 'WINTERS H S’,
 'BROWNWOOD ACCELERATED H S’,
 'PILOT POINT H S’,
 'NEWTON H S’,
 'VEGA H S’,
 'DICKINSON H S’,
 'HENRY FORD ACADEMY ALAMEDA SCHOOL FOR ART + DESIGN’,
 'LUDI PENA MARTIN ACCELERATED EDUCATION CENTER’,
 'ROWE H S’,
 'EVERMAN ACADEMY H S’,
 'CHARLOTTE H S’,
 'SAN MARCOS H S’,
 'BEAUMONT ISD EARLY COLLEGE H S’,
 'NORTH SIDE H S’,
 'BANQUETE H S’,
 'DAN CHADWICK CAMPUS’,
 'SWEETWATER H S’,
 'EMPOWERMENT H S’,
 'LAMESA DAEP’,
 'BURKBURNETT H S’,
 'FOUNDERS CLASSICAL ACADEMY - FRISCO’,
 'LLANO H S’,
 'TRAVIS H S OF CHOICE’,
 'UPLIFT GRAND H S’,
 'BYRON NELSON H S’,
 'DAEP’,
 'PREMIER H S HOUSTON GALLERY NORTH’,
 'HIRSCHI H S’,
 'KIPP AUSTIN COLLEGIATE’,
 'PSJA SOUTHWEST EARLY COLLEGE H S’,
 'DENTON COUNTY JJAEP CFB CAMPUS’,
 'ECONOMEDES H S’,
 'ARISTOI CLASSICAL ACADEMY']

In [3]:
schools=['CHINA SPRING H S', 
         'SOCORRO H S',
         'BRIDGE CITY H S',
         'QUANAH H S',
         'PREMIER HIGH SCHOOL-CANYON',
         'N GARLAND H S',
         'TRIUMPH PUBLIC HIGH SCHOOLS-EL PASO WEST',
         'SALADO H S',
         'BUSHLAND H S',
         'MABANK H S',
         'SAM HOUSTON H S',
         'COLUMBIA H S',
         'YSLETA H S',
         'KASHMERE H S',
         'KERR H S',
         'ILTEXAS GARLAND H S',
         'CAREER & TECH ED CTR',
         'SOUTH HILLS H S',
         'LIGHTHOUSE HIGH',
         'PORT NECHES-GROVES H S',
         'BLANSON CTE H S',
         'ANSON H S',
         'ROUND ROCK H S',
         'GAINESVILLE H S',
         'RIO HONDO H S',
         'SCHOOL OF BUSINESS AND MANAGEMENT']

In [4]:
url = 'https://rptsvr1.tea.texas.gov/cgi/sas/broker?_service=marykay&_program=perfrept.perfmast.sas&_debug=0&lev=C&id=161920001&prgopt=reports%2Ftapr%2Fperformance.sas'

response = get(url)

In [5]:
soup = BeautifulSoup(response.content, 'html.parser')

In [6]:
response

In [7]:
soup.find_all('td', class_='r t data')[194].text

'    90%   '

In [8]:
soup.find_all('td', class_='r t data')

[<td class="r t data">    65%   </td>,
 <td class="r t data">    84%   </td>,
 <td class="r t data" style=" font-weight: bold;">    85%   </td>,
 <td class="r t data">    70%   </td>,
 <td class="r t data">    76%   </td>,
 <td class="r t data">    89%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    39%   </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    84%   </td>,
 <td class="r t data">    86%   </td>,
 <td class="r t data">    77%   </td>,
 <td class="r t data">    63%   </td>,
 <td class="r t data">    67%   </td>,
 <td class="r t data">    80%   </td>,
 <td class="r t data" style=" font-weight: bold;">    80%   </td>,
 <td class="r t data">    53%   </td>,
 <td class="r t data">    71%   </td>,
 <td class="r t data">    86%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    34%   </td>,
 <td class="r t data">    89%   </td>,
 <td class="r t data">    84%   </td>,
 <td class="r t data">    70%   </td>,
 <td class="r t data">    61%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    47%   </td>,
 <td class="r t data">    62%   </td>,
 <td class="r t data" style=" font-weight: bold;">    62%   </td>,
 <td class="r t data">    35%   </td>,
 <td class="r t data">    61%   </td>,
 <td class="r t data">    66%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">    83%   </td>,
 <td class="r t data">    10%   </td>,
 <td class="r t data">    80%   </td>,
 <td class="r t data">    66%   </td>,
 <td class="r t data">    54%   </td>,
 <td class="r t data">    49%   </td>,
 <td class="r t data">    38%   </td>,
 <td class="r t data">    50%   </td>,
 <td class="r t data">    69%   </td>,
 <td class="r t data" style=" font-weight: bold;">    69%   </td>,
 <td class="r t data">    40%   </td>,
 <td class="r t data">    56%   </td>,
 <td class="r t data">    75%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    24%   </td>,
 <td class="r t data">    67%   </td>,
 <td class="r t data">    72%   </td>,
 <td class="r t data">    59%   </td>,
 <td class="r t data">    38%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    11%   </td>,
 <td class="r t data">    12%   </td>,
 <td class="r t data" style=" font-weight: bold;">    12%   </td>,
 <td class="r t data">     4%   </td>,
 <td class="r t data">    12%   </td>,
 <td class="r t data">    12%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">    17%   </td>,
 <td class="r t data">     2%   </td>,
 <td class="r t data">    20%   </td>,
 <td class="r t data">    14%   </td>,
 <td class="r t data">     6%   </td>,
 <td class="r t data">     2%   </td>,
 <td class="r t data">     0%   </td>,
 <td class="r t data">    12%   </td>,
 <td class="r t data">    19%   </td>,
 <td class="r t data" style=" font-weight: bold;">    19%   </td>,
 <td class="r t data">     7%   </td>,
 <td class="r t data">    15%   </td>,
 <td class="r t data">    21%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">     0%   </td>,
 <td class="r t data">     7%   </td>,
 <td class="r t data">     0%   </td>,
 <td class="r t data">    21%   </td>,
 <td class="r t data">    13%   </td>,
 <td class="r t data">     7%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    72%   </td>,
 <td class="r t data">    86%   </td>,
 <td class="r t data" style=" font-weight: bold;">    87%   </td>,
 <td class="r t data">    71%   </td>,
 <td class="r t data">    83%   </td>,
 <td class="r t data">    90%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    39%   </td>,
 <td class="r t data">    89%   </td>,
 <td class="r t data">    89%   </td>,
 <td class="r t data">    82%   </td>,
 <td class="r t data">    82%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    71%   </td>,
 <td class="r t data">    84%   </td>,
 <td class="r t data" style=" font-weight: bold;">    85%   </td>,
 <td class="r t data">    70%   </td>,
 <td class="r t data">    85%   </td>,
 <td class="r t data">    86%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    38%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    89%   </td>,
 <td class="r t data">    73%   </td>,
 <td class="r t data">    71%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    55%   </td>,
 <td class="r t data">    75%   </td>,
 <td class="r t data" style=" font-weight: bold;">    76%   </td>,
 <td class="r t data">    47%   </td>,
 <td class="r t data">    68%   </td>,
 <td class="r t data">    80%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    19%   </td>,
 <td class="r t data">    56%   </td>,
 <td class="r t data">    78%   </td>,
 <td class="r t data">    69%   </td>,
 <td class="r t data">    63%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    57%   </td>,
 <td class="r t data">    74%   </td>,
 <td class="r t data" style=" font-weight: bold;">    74%   </td>,
 <td class="r t data">    55%   </td>,
 <td class="r t data">    80%   </td>,
 <td class="r t data">    75%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">    75%   </td>,
 <td class="r t data">    19%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    79%   </td>,
 <td class="r t data">    61%   </td>,
 <td class="r t data">    56%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">     9%   </td>,
 <td class="r t data">    20%   </td>,
 <td class="r t data" style=" font-weight: bold;">    20%   </td>,
 <td class="r t data">     6%   </td>,
 <td class="r t data">    12%   </td>,
 <td class="r t data">    24%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">    17%   </td>,
 <td class="r t data">     6%   </td>,
 <td class="r t data">     0%   </td>,
 <td class="r t data">    21%   </td>,
 <td class="r t data">    18%   </td>,
 <td class="r t data">     8%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    11%   </td>,
 <td class="r t data">    19%   </td>,
 <td class="r t data" style=" font-weight: bold;">    19%   </td>,
 <td class="r t data">    10%   </td>,
 <td class="r t data">    13%   </td>,
 <td class="r t data">    23%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">    25%   </td>,
 <td class="r t data">     0%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    24%   </td>,
 <td class="r t data">     6%   </td>,
 <td class="r t data">     8%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    76%   </td>,
 <td class="r t data">    92%   </td>,
 <td class="r t data" style=" font-weight: bold;">    90%   </td>,
 <td class="r t data">    83%   </td>,
 <td class="r t data">    88%   </td>,
 <td class="r t data">    93%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">    88%   </td>,
 <td class="r t data">    69%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    91%   </td>,
 <td class="r t data">    88%   </td>,
 <td class="r t data">    85%   </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    73%   </td>,
 <td class="r t data">    86%   </td>,
 <td class="r t data" style=" font-weight: bold;">    84%   </td>,
 <td class="r t data">    62%   </td>,
 <td class="r t data">    82%   </td>,
 <td class="r t data">    87%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    61%   </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    86%   </td>,
 <td class="r t data">    79%   </td>,
 <td class="r t data">    71%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    43%   </td>,
 <td class="r t data">    60%   </td>,
 <td class="r t data" style=" font-weight: bold;">    54%   </td>,
 <td class="r t data">    43%   </td>,
 <td class="r t data">    54%   </td>,
 <td class="r t data">    58%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">    38%   </td>,
 <td class="r t data">    28%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    60%   </td>,
 <td class="r t data">    42%   </td>,
 <td class="r t data">    44%   </td>,
 <td class="r t data">    17%   </td>,
 <td class="r t data">    41%   </td>,
 <td class="r t data">    52%   </td>,
 <td class="r t data" style=" font-weight: bold;">    44%   </td>,
 <td class="r t data">     8%   </td>,
 <td class="r t data">    33%   </td>,
 <td class="r t data">    52%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">    60%   </td>,
 <td class="r t data">    25%   </td>,
 <td class="r t data">    78%   </td>,
 <td class="r t data">    53%   </td>,
 <td class="r t data">    23%   </td>,
 <td class="r t data">    22%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    27%   </td>,
 <td class="r t data">    36%   </td>,
 <td class="r t data" style=" font-weight: bold;">    29%   </td>,
 <td class="r t data">    22%   </td>,
 <td class="r t data">    27%   </td>,
 <td class="r t data">    32%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">    25%   </td>,
 <td class="r t data">     8%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    34%   </td>,
 <td class="r t data">    18%   </td>,
 <td class="r t data">    24%   </td>,
 <td class="r t data">    17%   </td>,
 <td class="r t data">    23%   </td>,
 <td class="r t data">    32%   </td>,
 <td class="r t data" style=" font-weight: bold;">    23%   </td>,
 <td class="r t data">     0%   </td>,
 <td class="r t data">    24%   </td>,
 <td class="r t data">    24%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">    40%   </td>,
 <td class="r t data">     7%   </td>,
 <td class="r t data">    33%   </td>,
 <td class="r t data">    29%   </td>,
 <td class="r t data">     9%   </td>,
 <td class="r t data">     5%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    83%   </td>,
 <td class="r t data">    96%   </td>,
 <td class="r t data" style=" font-weight: bold;">    96%   </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    87%   </td>,
 <td class="r t data">    99%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    68%   </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    97%   </td>,
 <td class="r t data">    94%   </td>,
 <td class="r t data">    94%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    82%   </td>,
 <td class="r t data">    96%   </td>,
 <td class="r t data" style=" font-weight: bold;">    96%   </td>,
 <td class="r t data">    85%   </td>,
 <td class="r t data">    92%   </td>,
 <td class="r t data">    98%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    72%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    98%   </td>,
 <td class="r t data">    86%   </td>,
 <td class="r t data">    90%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    55%   </td>,
 <td class="r t data">    81%   </td>,
 <td class="r t data" style=" font-weight: bold;">    82%   </td>,
 <td class="r t data">    64%   </td>,
 <td class="r t data">    61%   </td>,
 <td class="r t data">    91%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    32%   </td>,
 <td class="r t data">    67%   </td>,
 <td class="r t data">    84%   </td>,
 <td class="r t data">    77%   </td>,
 <td class="r t data">    72%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    55%   </td>,
 <td class="r t data">    81%   </td>,
 <td class="r t data" style=" font-weight: bold;">    83%   </td>,
 <td class="r t data">    65%   </td>,
 <td class="r t data">    82%   </td>,
 <td class="r t data">    86%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">    86%   </td>,
 <td class="r t data">    44%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    89%   </td>,
 <td class="r t data">    60%   </td>,
 <td class="r t data">    66%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    21%   </td>,
 <td class="r t data">    39%   </td>,
 <td class="r t data" style=" font-weight: bold;">    39%   </td>,
 <td class="r t data">    21%   </td>,
 <td class="r t data">    24%   </td>,
 <td class="r t data">    43%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">    88%   </td>,
 <td class="r t data">     8%   </td>,
 <td class="r t data">    17%   </td>,
 <td class="r t data">    41%   </td>,
 <td class="r t data">    32%   </td>,
 <td class="r t data">    24%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    22%   </td>,
 <td class="r t data">    45%   </td>,
 <td class="r t data" style=" font-weight: bold;">    46%   </td>,
 <td class="r t data">    30%   </td>,
 <td class="r t data">    31%   </td>,
 <td class="r t data">    52%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">    57%   </td>,
 <td class="r t data">    11%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    53%   </td>,
 <td class="r t data">    22%   </td>,
 <td class="r t data">    30%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    89%   </td>,
 <td class="r t data">    97%   </td>,
 <td class="r t data" style=" font-weight: bold;">    98%   </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    96%   </td>,
 <td class="r t data">    97%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    69%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    97%   </td>,
 <td class="r t data">    98%   </td>,
 <td class="r t data">    96%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    88%   </td>,
 <td class="r t data">    96%   </td>,
 <td class="r t data" style=" font-weight: bold;">    97%   </td>,
 <td class="r t data">    91%   </td>,
 <td class="r t data">    94%   </td>,
 <td class="r t data">    98%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    71%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    97%   </td>,
 <td class="r t data">    97%   </td>,
 <td class="r t data">    91%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    68%   </td>,
 <td class="r t data">    89%   </td>,
 <td class="r t data" style=" font-weight: bold;">    90%   </td>,
 <td class="r t data">    65%   </td>,
 <td class="r t data">    90%   </td>,
 <td class="r t data">    92%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">    89%   </td>,
 <td class="r t data">    63%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    91%   </td>,
 <td class="r t data">    84%   </td>,
 <td class="r t data">    85%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    69%   </td>,
 <td class="r t data">    77%   </td>,
 <td class="r t data" style=" font-weight: bold;">    80%   </td>,
 <td class="r t data">    45%   </td>,
 <td class="r t data">    82%   </td>,
 <td class="r t data">    83%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    21%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    80%   </td>,
 <td class="r t data">    77%   </td>,
 <td class="r t data">    76%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    42%   </td>,
 <td class="r t data">    63%   </td>,
 <td class="r t data" style=" font-weight: bold;">    64%   </td>,
 <td class="r t data">    47%   </td>,
 <td class="r t data">    59%   </td>,
 <td class="r t data">    69%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">    78%   </td>,
 <td class="r t data">     6%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    67%   </td>,
 <td class="r t data">    55%   </td>,
 <td class="r t data">    58%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    43%   </td>,
 <td class="r t data">    44%   </td>,
 <td class="r t data" style=" font-weight: bold;">    47%   </td>,
 <td class="r t data">    36%   </td>,
 <td class="r t data">    36%   </td>,
 <td class="r t data">    51%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">     7%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    46%   </td>,
 <td class="r t data">    52%   </td>,
 <td class="r t data">    52%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">    92%   </td>,
 <td class="r t data">    97%   </td>,
 <td class="r t data" style=" font-weight: bold;">    97%   </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">   100%   </td>,
 <td class="r t data">    95%   </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">*         </td>,
 <td class="r t data">-         </td>,
 <td class="r t data">-         </td>,

In [9]:
url2 = 'https://rptsvr1.tea.texas.gov/cgi/sas/broker?_service=marykay&_program=perfrept.perfmast.sas&_debug=0&ccyy=2022&lev=C&id=161920001&prgopt=reports/tapr/student.sas'
response2 = get(url2)

In [10]:
response2

In [11]:
soup2 = BeautifulSoup(response2.content, 'html.parser')

In [89]:
soup2.find_all('td', class_='r b data')[241].text

'     1.3%'

In [14]:
soup2.find_all('td', class_='r b data')[217].text

'    29.6%'

In [15]:
url3 = 'https://rptsvr1.tea.texas.gov/cgi/sas/broker?_service=marykay&_program=perfrept.perfmast.sas&_debug=0&ccyy=2022&lev=C&id=161920001&prgopt=reports/tapr/staff.sas'
response3 = get(url3)

In [16]:
response3

In [17]:
soup3 = BeautifulSoup(response3.content, 'html.parser')

In [21]:
soup3.find_all('td', class_='r b data')[-43].text

'   $54,336'

In [28]:
soup3.find_all('td', class_='r b data')[-106].text

'     5.3%'

In [30]:
soup3.find_all('td', class_='r b data')[-114].text

'    23.2%'

In [33]:
soup3.find_all('td', class_='r b data')[-83].text

'      13.6'

In [34]:
url4 = 'https://rptsvr1.tea.texas.gov/cgi/sas/broker?_service=marykay&_service=appserv&_debug=0&_program=sfadhoc.new_Campus_actual21.sas&which_camp=161920001'
response4 = get(url4)

In [35]:
soup4 = BeautifulSoup(response4.content, 'html.parser')

In [36]:
response4

In [42]:
soup4.find_all('td', class_='r data')[31].text

'              $7,089'

In [43]:
soup4.find_all('td', class_='r data')[91].text

'                $734'

In [58]:
school=soup3.find_all('td', class_='c systemtitle3')[0].text
school

'CHINA SPRING H S (161920001) - CHINA SPRING ISD - MCLENNAN COUNTY'

In [47]:
chinaspring={'eng1': soup.find_all('td', class_='r t data')[2].text, 
 'eng2': soup.find_all('td', class_='r t data')[98].text, 
 'algebra': soup.find_all('td', class_='r t data')[194].text,
 'biology': soup.find_all('td', class_='r t data')[290].text, 
 'history': soup.find_all('td', class_='r t data')[386].text, 
 'ebel': soup2.find_all('td', class_='r b data')[241].text,
 'econdis': soup2.find_all('td', class_='r b data')[217].text,
 'salary': soup3.find_all('td', class_='r b data')[-43].text,
 'masters': soup3.find_all('td', class_='r b data')[-114].text,
 'doct': soup3.find_all('td', class_='r b data')[-110].text,
 'beginning_teach': soup3.find_all('td', class_='r b data')[-106].text,
 'ex_5': soup3.find_all('td', class_='r b data')[-102].text,
 'ex_10': soup3.find_all('td', class_='r b data')[-98].text,
 'ex_1120': soup3.find_all('td', class_='r b data')[-94].text,
 'ex_2130': soup3.find_all('td', class_='r b data')[-90].text,
 'ex_plus': soup3.find_all('td', class_='r b data')[-86].text,
 'extra_fund': soup4.find_all('td', class_='r data')[91].text,
 'all_fund': soup4.find_all('td', class_='r data')[31].text,
 'ratio': soup3.find_all('td', class_='r b data')[-83].text}

In [50]:
chinaspring

{'eng1': '    85%   ',
 'eng2': '    87%   ',
 'algebra': '    90%   ',
 'biology': '    96%   ',
 'history': '    98%   ',
 'ebel': '     1.3%',
 'econdis': '    29.6%',
 'salary': '   $54,336',
 'masters': '    23.2%',
 'doct': '     0.7%',
 'beginning_teach': '     5.3%',
 'ex_5': '    23.8%',
 'ex_10': '    13.5%',
 'ex_1120': '    35.9%',
 'ex_2130': '    15.8%',
 'ex_plus': '     5.8%',
 'extra_fund': '                $734',
 'all_fund': '              $7,089',
 'ratio': '      13.6'}

In [53]:
pd.DataFrame(chinaspring, index=['China Spring HS'])

,eng1,eng2,algebra,biology,history,ebel,econdis,salary,masters,doct,beginning_teach,ex_5,ex_10,ex_1120,ex_2130,ex_plus,extra_fund,all_fund,ratio
China Spring HS,85%,87%,90%,96%,98%,1.3%,29.6%,"$54,336",23.2%,0.7%,5.3%,23.8%,13.5%,35.9%,15.8%,5.8%,$734,"$7,089",13.6

## make function

In [90]:
def get_features(school_id):
    
    url1=f'https://rptsvr1.tea.texas.gov/cgi/sas/broker?_service=marykay&_program=perfrept.perfmast.sas&_debug=0&lev=C&id={school_id}&prgopt=reports%2Ftapr%2Fperformance.sas'
    url2=f'https://rptsvr1.tea.texas.gov/cgi/sas/broker?_service=marykay&_program=perfrept.perfmast.sas&_debug=0&ccyy=2022&lev=C&id={school_id}&prgopt=reports/tapr/student.sas'
    url3=f'https://rptsvr1.tea.texas.gov/cgi/sas/broker?_service=marykay&_program=perfrept.perfmast.sas&_debug=0&ccyy=2022&lev=C&id={school_id}&prgopt=reports/tapr/staff.sas'
    url4=f'https://rptsvr1.tea.texas.gov/cgi/sas/broker?_service=marykay&_service=appserv&_debug=0&_program=sfadhoc.new_Campus_actual21.sas&which_camp={school_id}'
    
    response1=get(url1)
    soup1 = BeautifulSoup(response1.content, 'html.parser')
    response2=get(url2)
    soup2 = BeautifulSoup(response2.content, 'html.parser')
    response3=get(url3)
    soup3 = BeautifulSoup(response3.content, 'html.parser')
    response4=get(url4)
    soup4 = BeautifulSoup(response4.content, 'html.parser')
    
    
    chinaspring={
        'school_id': [school_id],
        'eng1': [soup.find_all('td', class_='r t data')[2].text], 
        'eng2': [soup.find_all('td', class_='r t data')[98].text], 
        'algebra': [soup.find_all('td', class_='r t data')[194].text],
        'biology': [soup.find_all('td', class_='r t data')[290].text], 
        'history': [soup.find_all('td', class_='r t data')[386].text], 
        'ebel': [soup2.find_all('td', class_='r b data')[241].text],
        'econdis': [soup2.find_all('td', class_='r b data')[217].text],
        'salary': [soup3.find_all('td', class_='r b data')[-43].text],
        'masters': [soup3.find_all('td', class_='r b data')[-114].text],
        'doct': [soup3.find_all('td', class_='r b data')[-110].text],
        'beginning_teach': [soup3.find_all('td', class_='r b data')[-106].text],
        'ex_5': [soup3.find_all('td', class_='r b data')[-102].text],
        'ex_10': [soup3.find_all('td', class_='r b data')[-98].text],
        'ex_1120': [soup3.find_all('td', class_='r b data')[-94].text],
        'ex_2130': [soup3.find_all('td', class_='r b data')[-90].text],
        'ex_plus': [soup3.find_all('td', class_='r b data')[-86].text],
        'extra_fund': [soup4.find_all('td', class_='r data')[91].text],
        'all_fund': [soup4.find_all('td', class_='r data')[31].text],
        'ratio': [soup3.find_all('td', class_='r b data')[-83].text]
    }
    add=pd.DataFrame(chinaspring)
    return add

In [93]:
get_features('019907109')

,school_id,eng1,eng2,algebra,biology,history,ebel,econdis,salary,masters,doct,beginning_teach,ex_5,ex_10,ex_1120,ex_2130,ex_plus,extra_fund,all_fund,ratio
0,019907109,85%,87%,90%,96%,98%,25.8%,83.6%,"$53,129",28.3%,0.0%,2.4%,23.2%,15.5%,34.4%,17.2%,7.2%,$53,"$6,436",15.9

In [78]:
pd.DataFrame({
        'school_id': [],
        'eng1': [], 
        'eng2': [], 
        'algebra': [],
        'biology': [], 
        'history': [], 
        'ebel': [],
        'econdis': [],
        'salary': [],
        'masters': [],
        'doct': [],
        'beginning_teach': [],
        'ex_5': [],
        'ex_10': [],
        'ex_1120': [],
        'ex_2130': [],
        'ex_plus': [],
        'extra_fund': [],
        'all_fund': [],
        'ratio': []
    })

Empty DataFrame
Columns: [school_id, eng1, eng2, algebra, biology, history, ebel, econdis, salary, masters, doct, beginning_teach, ex_5, ex_10, ex_1120, ex_2130, ex_plus, extra_fund, all_fund, ratio]
Index: []

In [102]:
def all_schools(school_id):
    all_info=pd.DataFrame({
        'school_id': [],
        'eng1': [], 
        'eng2': [], 
        'algebra': [],
        'biology': [], 
        'history': [], 
        'ebel': [],
        'econdis': [],
        'salary': [],
        'masters': [],
        'doct': [],
        'beginning_teach': [],
        'ex_5': [],
        'ex_10': [],
        'ex_1120': [],
        'ex_2130': [],
        'ex_plus': [],
        'extra_fund': [],
        'all_fund': [],
        'ratio': []
    })
    for n in school_id:
        try:
            school=get_features(n)
            all_info=pd.concat([all_info, school], ignore_index=True)
        except:
            continue
    return all_info

In [103]:
test= all_schools(['161920001', '1902001', '019907109'])

In [104]:
test

,school_id,eng1,eng2,algebra,biology,history,ebel,econdis,salary,masters,doct,beginning_teach,ex_5,ex_10,ex_1120,ex_2130,ex_plus,extra_fund,all_fund,ratio
0,161920001,85%,87%,90%,96%,98%,1.3%,29.6%,"$54,336",23.2%,0.7%,5.3%,23.8%,13.5%,35.9%,15.8%,5.8%,$734,"$7,089",13.6
1,019907109,85%,87%,90%,96%,98%,25.8%,83.6%,"$53,129",28.3%,0.0%,2.4%,23.2%,15.5%,34.4%,17.2%,7.2%,$53,"$6,436",15.9